BEGIN TRANSACTION;

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS patient CASCADE;
DROP TABLE IF EXISTS provider CASCADE;
DROP TABLE IF EXISTS office CASCADE;
DROP TABLE IF EXISTS provider_office CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS responses CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;

DROP SEQUENCE IF EXISTS user_serial;
DROP SEQUENCE IF EXISTS patient_serial;
DROP SEQUENCE IF EXISTS provider_serial;
DROP SEQUENCE IF EXISTS appointment_serial;
DROP SEQUENCE IF EXISTS office_serial;
DROP SEQUENCE IF EXISTS review_serial;
DROP SEQUENCE IF EXISTS response_serial;

COMMIT TRANSACTION;

